  userservice:
    image: raydeng83/userservice
    mem_limit: 1073741824
    ports:
       - "8081:8081"
    environment:
      ENCRYPT_KEY: "IMSYMMETRIC"
      CONFIGSERVER_URI: "http://configservice:8888"